server:
    port: 80

spring:
    application:
        name: API-GATEWAY
    cloud:
        gateway:
            routes:
                -   id: EMPLOYEE-SERVICE
                    uri: lb://EMPLOYEE-SERVICE
                    predicates:
                        - Path=/api/employees/**
                -   id: DEPARTMENT-SERVICE
                    uri: lb://DEPARTMENT-SERVICE
                    predicates:
                        - Path=/api/departments/**

eureka:
    client:
        register-with-eureka: true
        fetch-registry: true
        service-url:
            defaultZone: http://localhost:8761/eureka/
    instance:
        hostname: localhost